= RESTEasy support of Spring REST annotations

The module shows an example of using RESTEasy to support Spring REST annotations.

== Building the project

[source,bash]
----
$ mvn clean install

----

== Running the project and manually testing it

[source,bash]
----
$ mvn wildfly:run

----

Using the `curl` command to access this URL:

[source,bash]
----
$ curl http://localhost:8080/resteasy-spring-rest/spring

----

It will return `Spring is coming!` from server side. And the resource class from server side is using Spring REST annotations:

[source,java]
----
@RestController
@RequestMapping("/spring")
public class SpringRestAnnotationResource {

    @GetMapping("/")
    public String get() {
        return "Spring is coming!";
    }
}

----

== Deploying The Project To WildFly

This example has embedded `wildfly-maven-plugin` embedded, so it can be deployed to a managed WildFly server by running the Maven command. Run the following command to build the example, download WildFly server, start the server and finish deployment automatically:

[source,bash]
----
$ mvn wildfly:run

----

After the embedded WildFly server is downloaded and run, access the example service with following `curl` command:

[source,bash]
----
$ curl http://localhost:8080/resteasy-spring-rest/spring

----

And it will print the output result:

[source,bash]
----
Spring is coming!
----